# Generated by Django 3.2.16 on 2023-01-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
