# Generated by Django 3.2.16 on 2023-01-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_alter_userprofile_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='address',
        ),
    ]
