# Generated by Django 3.2.16 on 2023-04-24 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0013_userprofile_age_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='expiration_time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 24, 21, 13, 19, 947519)),
        ),
    ]
