# Generated by Django 3.2.16 on 2023-04-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0014_userprofile_blog_access_userprofile_category_access_and_more'),
        ('CustomUser', '0015_alter_resetpassword_expiration_time'),
    ]

    operations = [
    ]
