# Generated by Django 4.1.5 on 2023-04-25 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0016_merge_20230424_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='expiration_time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 25, 6, 35, 39, 579020)),
        ),
    ]
