# Generated by Django 4.1.5 on 2023-05-22 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0018_alter_resetpassword_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='expiration_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 22, 15, 18, 26, 229549)),
        ),
    ]
