# Generated by Django 4.1.5 on 2023-03-18 20:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_alter_discountcode_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 1, 20, 44, 14, 721197)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 20, 44, 14, 720953)),
        ),
    ]
