# Generated by Django 3.2.16 on 2023-04-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_alter_discountcode_expire_date_and_more'),
        ('Product', '0018_auto_20230424_2139'),
    ]

    operations = [
    ]
