# Generated by Django 4.1.5 on 2023-04-25 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_merge_20230424_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 9, 6, 33, 39, 584092)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 6, 33, 39, 583686)),
        ),
    ]
