# Generated by Django 4.1.5 on 2023-05-22 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_alter_discountcode_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='en_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='en_name',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 15, 16, 26, 234611)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 15, 16, 26, 234208)),
        ),
    ]
