# Generated by Django 3.2.16 on 2023-07-16 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0023_category_parent_alter_discountcode_expire_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_price',
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 21, 57, 19, 134300)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 21, 57, 19, 134041)),
        ),
    ]
